name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-tgtlutmhzv1gy5p4.cn-shanghai.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/library/nginx:latest docker://crpi-tgtlutmhzv1gy5p4.cn-shanghai.personal.cr.aliyuncs.com/temps/ngnix:latest
         skopeo copy docker://docker.io/library/openjdk:11-jre docker://crpi-tgtlutmhzv1gy5p4.cn-shanghai.personal.cr.aliyuncs.com/temps/openjdk:11-jre
